--------------------------------------------------------
-----------------------  Variables  --------------------
--------------------------------------------------------

name: Variables
########################  Paths to use  ###############################

# Raw data path: where to find the raw data ?
raw_data_path: "/shared/projects/pacobar/archive/rawfile/"
raw_vcf_file: "/shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/outputs/Processing_of_short_read_data/08_Full_VCF/"

# Pop_map: path to the pop_map directory. This path is required to run the snakemake. It should contain one text file per population to analyse.
# For each population, the text file should contain the list of the samples to run the analysis on, without the extensions.
pop_maps: "/shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/scripts/A_Genetic_analysis/02_Filter_VCF_Files/POP_MAP/"

# Folder where all the temporary files will be stored
tmp_path: "/shared/scratch/pacobar/bpajot/tmp/Filter_VCF_Files/"

# Where to save the final output data
output_path: "/shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/outputs/Filter_VCF_Files/"

# Where is the reference genome
Reference_genome: "/shared/projects/pacobar/input/reference/Reference_Littorina_saxatilis_reshape.fa"



########################  Cut chromosomes  ###############################
# We need to break the chromosomes in the analysis into bins of a given size to be able to parallelise on the 
# chosen bins. To do so, we use this parameter (bin_size) to have the maximum number of bases in the chromosomal bins
# The default value in the function that cuts the chromosomes into bins is 1e6, but this parameter can be changed
bin_size: 1e7

########################  Missing rate  ###############################
# We need to use a missing data threshold value on the final vcf. The chosen value (between 0 and 1) will be used as 
# a maximum of missing data. For axample if you choose 0.95, only data with less than 5% of missing data will be kept
missing_rate: 0.95

########################  Heterozygosity  ###############################
# We need to use a heterozygosity threshold value on the final vcf. The chosen value (between 0 and 1) will be used as 
# a maximum of heterozygosity. 
Hobs: 0.55

########################  Strand bias (SP)  ###############################
# We need to use a SP threshold value on the final vcf. The chosen value will be used as 
# a maximum of SP. 
cutoff: 3


---------------------------------------------------------
-----------------------  Profile  -----------------------
---------------------------------------------------------
name: Profile
########################  Cluster identification  ###############################
cluster:
  mkdir -p /shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/scripts/A_Genetic_analysis/02_Filter_VCF_Files/logs/{rule}/error_files/ &&
  mkdir -p /shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/scripts/A_Genetic_analysis/02_Filter_VCF_Files/logs/{rule}/logs/ &&
  sbatch
    --account=pacobar
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=/shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/scripts/A_Genetic_analysis/02_Filter_VCF_Files/logs/{rule}/logs/{rule}-{wildcards}-%j.out
    --error=/shared/projects/pacobar/finalresult/bpajot/Stage_Roscoff/scripts/A_Genetic_analysis/02_Filter_VCF_Files/logs/{rule}/error_files/{rule}-{wildcards}-%j.err
    --parsable

########################  Resources to use  ###############################
default-resources:
  - partition=fast
  - mem_mb=8000
  - tmpdir="/shared/scratch/pacobar/bpajot/tmp/Filter_VCF_Files/"


########################  Parameters to use for the snakemake  ###############################
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 30
jobs: 40
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True



---------------------------------------------------------
---------------------  Environments  --------------------
---------------------------------------------------------
name: Environments
########################  Dependencies  ###############################
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools = 1.16
  - vcftools = 0.1.16
  - r = 4.3.1
  - r-tidyverse = 2.0.0
  - r-argparse
  - r-ggpubr
  - r-adegenet
  - r-vcfR
  - r-pegas
  - r-pacman
