--------------------------------------------------------
-----------------------  Variables  --------------------
--------------------------------------------------------

name: Variables
########################  Paths to use  ###############################
# Inputs:
# VCF files
## Large one on which to run the HMM
vcf_file: "../../Output/Sweden_France_parallelism/02_Filter_VCF/07_SP/VCF_File.vcf.gz"
## Smaller one on which to get the name of the individuals to keep to look at the differentiation 
vcf_small: "../../Output/Sweden_France_parallelism/02_Filter_VCF/09_Maf_thin/VCF_File.vcf.gz"

# Metadata file
metadata: "../../Input_Data/Data/data_Fabalis_resequencing_Basile.xlsx"
# Folder where all the temporary files will be stored
tmp_path: "../../Output/tmp/HMM/"

# Where to save the final output data
output_path: "../../Output/Sweden_France_parallelism/03_HMM/"

# Reference individuals
ref_indiv_path: "../../Output/Data/Reference_indivs_expos/"

# Maf value
MAF: 0.3

---------------------------------------------------------
-----------------------  Profile  -----------------------
---------------------------------------------------------
name: Profile
########################  Cluster identification  ###############################
cluster:
  mkdir -p ./logs/{rule}/error_files/ &&
  mkdir -p ./logs/{rule}/logs/ &&
  sbatch
    --account=pacobar
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=./logs/{rule}/logs/{rule}-{wildcards}-%j.out
    --error=./logs/{rule}/error_files/{rule}-{wildcards}-%j.err
    --parsable

########################  Resources to use  ###############################
default-resources:
  - partition=fast
  - mem_mb=8000

########################  Parameters to use for the snakemake  ###############################
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 30
jobs: 40
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True



---------------------------------------------------------
---------------------  Environments  --------------------
---------------------------------------------------------
name: Environments
########################  Dependencies  ###############################
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - vcftools = 0.1.16
  # R and R packages
  - r = 4.3.1
  - r-pacman
  - r-HiddenMarkov
  - r-foreach
  - r-doParallel
  - r-argparse
  # Python and Python packages

