--------------------------------------------------------
-----------------------  Variables  --------------------
--------------------------------------------------------

name: Variables
########################  Paths to use  ###############################

# Raw data path: where to find the raw data ?
raw_data_path: "../../Output/SNP_calling/08_Full_VCF/"

# Pop_map: path to the pop_map directory. This path is required to run the snakemake. It should contain one text file per population to analyse.
# For each population, the text file should contain the list of the samples to run the analysis on, without the extensions.
pop_maps: "./Pop_map/"

# Folder where all the temporary files will be stored
tmp_path: "../../Output/tmp/"

# Where to save the final output data
output_path: "../../Output/"



########################  Cut chromosomes  ###############################
# We need to break the chromosomes in the analysis into bins of a given size to be able to parallelise on the 
# chosen bins. To do so, we use this parameter (bin_size) to have the maximum number of bases in the chromosomal bins
# The default value in the function that cuts the chromosomes into bins is 1e6, but this parameter can be changed
bin_size: 1e7

########################  Missing rate  ###############################
# We need to use a missing data threshold value on the final vcf. The chosen value (between 0 and 1) will be used as 
# a maximum of missing data. For axample if you choose 0.95, only data with less than 5% of missing data will be kept
missing_rate: 0.95

########################  Heterozygosity  ###############################
# We need to use a heterozygosity threshold value on the final vcf. The chosen value (between 0 and 1) will be used as 
# a maximum of heterozygosity. 
Hobs: 0.55

########################  Strand bias (SP)  ###############################
# We need to use a SP threshold value on the final vcf. The chosen value will be used as 
# a maximum of SP. 
cutoff: 3 
mac: 1
maf: 0.05
thin: 1000


---------------------------------------------------------
-----------------------  Profile  -----------------------
---------------------------------------------------------
name: Profile
########################  Resources to use and cluster identification  ###############################
default-resources:
  slurm_account: "'pacobar'"
  slurm_partition: "'fast'"
  partition: "'fast'"
  mem_mb: "'8000'"
  nodes: 1
  runtime: "'86400'" # One day

########################  Parameters to use for the snakemake  ###############################
executor: slurm
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: 40
jobs: 40
latency-wait: 30
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True


---------------------------------------------------------
---------------------  Environments  --------------------
---------------------------------------------------------
name: Environments
########################  Dependencies  ###############################
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools = 1.16
  - vcftools = 0.1.16
  # R and R packages
  - r = 4.3.1
  - r-tidyverse = 2.0.0
  - r-argparse
  - r-ggpubr
  - r-adegenet
  - r-vcfR
  - r-pegas
  - r-pacman
  # Python and Python packages
